model:
  name: 'MinkUNet34'
  out_classes: 19
  params:
    in_channels: 4
    out_channels: 19
  features:
    - coordinates
    - features

source_dataset:
  version: 'mini'
  name: 'SynLiDAR'
  dataset_path: '/path/to/SynLiDAR'
  mapping_path: '/path/to/cosmix-intensity/utils/datasets/_resources/synlidar_semantickitti.yaml'
  weights_path: '/path/to/cosmix-intensity/utils/datasets/_weights/synlidar2semantickitti_correct.npy'
  target: null
  voxel_size: 0.05
  num_pts: 80000
  ignore_label: -1
  augment_data: false
  transforms:
    train:
      - type: "RandomRotate"
        angle: [ -1, 1 ]
        axis: "z"
        center: [ 0, 0, 0 ]
        p: 0.5
      - type: "PointClip"
        point_cloud_range: [ -35.2, -35.2, -4, 35.2, 35.2, 2 ]
      - type: "RandomScale"
        scale: [ 0.9, 1.1 ]
      - type: "RandomFlip"
        p: 0.5
      - type: "RandomJitter"
        sigma: 0.005
        clip: 0.02
      - type: "GridSample"
        grid_size: 0.05
        hash_type: "fnv"
        mode: "train"
        keys: [ "coord", "strength", "segment" ]
        return_grid_coord: true
      - type: "ToTensor"
      - type: "Collect"
        keys: [ "coord", "grid_coord", "segment" ]
        feat_keys: [ "coord", "strength" ]
    val:
      - type: "PointClip"
        point_cloud_range: [ -35.2, -35.2, -4, 35.2, 35.2, 2 ]
      - type: "GridSample"
        grid_size: 0.05
        hash_type: "fnv"
        mode: "train"
        keys: [ "coord", "strength", "segment" ]
        return_grid_coord: true
      - type: "ToTensor"
      - type: "Collect"
        keys: [ "coord", "grid_coord", "segment" ]
        feat_keys: [ "coord", "strength" ]
    test:
      - type: "PointClip"
        point_cloud_range: [ -35.2, -35.2, -4, 35.2, 35.2, 2 ]

target_dataset:
  version: 'mini'
  name: 'SemanticKITTI'
  dataset_path: '/path/to/SemanticKitti/dataset/sequences'
  mapping_path: '/path/to/cosmix-intensity/utils/datasets/_resources/semantic-kitti.yaml'
  target: null
  voxel_size: 0.05
  num_pts: 80000
  ignore_label: -1
  augment_data: false
  transforms:
    train:
      - type: "RandomRotate"
        angle: [ -1, 1 ]
        axis: "z"
        center: [ 0, 0, 0 ]
        p: 0.5
      - type: "PointClip"
        point_cloud_range: [ -35.2, -35.2, -4, 35.2, 35.2, 2 ]
      - type: "RandomScale"
        scale: [ 0.9, 1.1 ]
      - type: "RandomFlip"
        p: 0.5
      - type: "RandomJitter"
        sigma: 0.005
        clip: 0.02
      - type: "GridSample"
        grid_size: 0.05
        hash_type: "fnv"
        mode: "train"
        keys: [ "coord", "strength", "segment" ]
        return_grid_coord: true
      - type: "ToTensor"
      - type: "Collect"
        keys: [ "coord", "grid_coord", "segment" ]
        feat_keys: [ "coord", "strength" ]
    val:
      - type: "PointClip"
        point_cloud_range: [ -35.2, -35.2, -4, 35.2, 35.2, 2 ]
      - type: "GridSample"
        grid_size: 0.05
        hash_type: "fnv"
        mode: "train"
        keys: [ "coord", "strength", "segment" ]
        return_grid_coord: true
      - type: "ToTensor"
      - type: "Collect"
        keys: [ "coord", "grid_coord", "segment" ]
        feat_keys: [ "coord", "strength" ]
    test:
      - type: "PointClip"
        point_cloud_range: [ -35.2, -35.2, -4, 35.2, 35.2, 2 ]

masked_dataset:
  augment_data: true
  augment_mask_data: true
  remove_overlap: false

pipeline:
  epochs: 3
  steps: null
  gpus: [0, 1]
  precision: 32
  seed: 1234
  save_dir: '/path/to/cosmix-intensity/experiments/idas/uda'

  dataloader:
    train_batch_size: 2
    val_batch_size: 8
    num_workers: 24

  optimizer:
    name: 'SGD'
    lr: 0.001

  scheduler:
    name: null

  lightning:
    check_val_every_n_epoch: 1
    clear_cache_int: 1
    resume_checkpoint: null
    val_check_interval: 1.0
    num_sanity_val_steps: 0

  wandb:
    run_name: 'CoSMix-adaptation-SynLiDAR2SemanticKITTI'
    project_name: 'cosmix-intensity'
    entity_name: 'cosmix-intensity'
    offline: false

adaptation:
  student_checkpoint: '/path/to/cosmix-intensity/experiments/pretrained/synlidar/semantickitti/2025_01_10_10:31_SOURCE-WARMUP-SynLiDAR2SemanticKITTI/checkpoints/epoch=99-step=2399.ckpt'
  teacher_checkpoint: '/path/to/cosmix-intensity/experiments/pretrained/synlidar/semantickitti/2025_01_10_10:31_SOURCE-WARMUP-SynLiDAR2SemanticKITTI/checkpoints/epoch=99-step=2399.ckpt'
  filtering: 'confidence'
  adaptive_weight: false
  oracle_rate: 0.0
  shuffle_batches: false
  compositional: false
  source_filtering: false
  propagation: false
  propagation_size: 0
  weighted_sampling: true
  self_paced: false
  is_mix3d: false
  is_mix3d_pseudo: false
  selection_perc: 0.5
  remove_class: null
  target_confidence_th: 0.90

  losses:
    source_criterion: 'SoftDICELoss'
    target_criterion: 'SoftDICELoss'
    other_criterion: null
    source_weight: 1.0
    target_weight: 1.0
    other_weight: 0.

  momentum:
    base_tau: 0.9
    final_tau: 0.9
    update_every: 500

